"""Add dynamic cost fields

Revision ID: 19d0cd3e569d
Revises: 40ae4a9db2bc
Create Date: 2026-05-07 06:06:55.607219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d0cd3e569d'
down_revision: Union[str, Sequence[str], None] = '40ae4a9db2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('proxy_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('proxy_cost')
        batch_op.drop_column('account_cost')

    # ### end Alembic commands ###
