"""Add profit optimization tracking

Revision ID: 246a003d17aa
Revises: d93eb72508ae
Create Date: 2026-05-04 00:57:52.267995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246a003d17aa'
down_revision: Union[str, Sequence[str], None] = 'd93eb72508ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niche_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('avg_conversion_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('niche_performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_niche_performance_category'), ['category'], unique=True)
        batch_op.create_index(batch_op.f('ix_niche_performance_id'), ['id'], unique=False)

    with op.batch_alter_table('generated_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diversity_penalty', sa.Integer(), nullable=True))

    with op.batch_alter_table('post_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_score', sa.Float(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_commission', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('estimated_commission')

    with op.batch_alter_table('post_queue', schema=None) as batch_op:
        batch_op.drop_column('profit_score')
        batch_op.drop_column('revenue')

    with op.batch_alter_table('generated_contents', schema=None) as batch_op:
        batch_op.drop_column('diversity_penalty')

    with op.batch_alter_table('niche_performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_niche_performance_id'))
        batch_op.drop_index(batch_op.f('ix_niche_performance_category'))

    op.drop_table('niche_performance')
    # ### end Alembic commands ###
