"""Add scaling and risk control

Revision ID: 67f04a4e85e1
Revises: 246a003d17aa
Create Date: 2026-05-04 03:34:46.391541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f04a4e85e1'
down_revision: Union[str, Sequence[str], None] = '246a003d17aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shadowbanned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('total_profit', sa.Float(), nullable=True))

    with op.batch_alter_table('post_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dynamic_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_queue', schema=None) as batch_op:
        batch_op.drop_column('dynamic_cost')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('total_profit')
        batch_op.drop_column('is_shadowbanned')

    # ### end Alembic commands ###
