"""Add TikTokVideoTrend model

Revision ID: 6b4bdf000798
Revises: 3d4bda84b684
Create Date: 2026-04-30 10:32:37.404350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4bdf000798'
down_revision: Union[str, Sequence[str], None] = '3d4bda84b684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiktok_video_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('product_keywords', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tiktok_video_trends', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tiktok_video_trends_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tiktok_video_trends_video_id'), ['video_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiktok_video_trends', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tiktok_video_trends_video_id'))
        batch_op.drop_index(batch_op.f('ix_tiktok_video_trends_id'))

    op.drop_table('tiktok_video_trends')
    # ### end Alembic commands ###
