"""add_viral_patterns_table

Revision ID: 7462cc508fc1
Revises: d93eb72508ae
Create Date: 2024-05-07 10:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7462cc508fc1'
down_revision: Union[str, None] = '19d0cd3e569d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viral_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viral_patterns_id'), 'viral_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_viral_patterns_language'), 'viral_patterns', ['language'], unique=False)
    op.create_index(op.f('ix_viral_patterns_pattern_type'), 'viral_patterns', ['pattern_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viral_patterns_pattern_type'), table_name='viral_patterns')
    op.drop_index(op.f('ix_viral_patterns_language'), table_name='viral_patterns')
    op.drop_index(op.f('ix_viral_patterns_id'), table_name='viral_patterns')
    op.drop_table('viral_patterns')
    # ### end Alembic commands ###
