"""add_trust_score

Revision ID: 7b3b320d39e3
Revises: 7462cc508fc1
Create Date: 2024-05-07 11:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3b320d39e3'
down_revision: Union[str, None] = '7462cc508fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('trust_score', sa.Float(), nullable=True, server_default='50.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'trust_score')
    # ### end Alembic commands ###
