"""Update models for production scale

Revision ID: d18a947e8e28
Revises: 16d239fe1557
Create Date: 2026-04-30 03:16:05.262782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18a947e8e28'
down_revision: Union[str, Sequence[str], None] = '16d239fe1557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=True))

    with op.batch_alter_table('generated_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('variant_name', sa.String(), nullable=True))

    with op.batch_alter_table('post_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_queue', schema=None) as batch_op:
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('generated_contents', schema=None) as batch_op:
        batch_op.drop_column('variant_name')
        batch_op.drop_column('content_mode')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('failed_attempts')
        batch_op.drop_column('rate_limit')

    # ### end Alembic commands ###
