"""Add ContentStrategyMetrics model

Revision ID: d93eb72508ae
Revises: 6b4bdf000798
Create Date: 2026-04-30 10:57:53.820265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93eb72508ae'
down_revision: Union[str, Sequence[str], None] = '6b4bdf000798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_strategy_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=True),
    sa.Column('metric_value', sa.String(), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=True),
    sa.Column('average_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_strategy_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_strategy_metrics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_strategy_metrics_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_strategy_metrics_metric_value'), ['metric_value'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_strategy_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_strategy_metrics_metric_value'))
        batch_op.drop_index(batch_op.f('ix_content_strategy_metrics_metric_type'))
        batch_op.drop_index(batch_op.f('ix_content_strategy_metrics_id'))

    op.drop_table('content_strategy_metrics')
    # ### end Alembic commands ###
